# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-30 19:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='image',
            field=models.ImageField(blank=True, default='../static/user.png', null=True, upload_to='perfil_Usuario/'),
        ),
    ]
